* CABSRT06 - MERGE THE SWITCHED/SPECIAL/UNE RATED STREAMS
* MVT SORT/MERGE CONTROL CARD.  MERGES THE THREE ELEMENT-TYPE
* RATED OUTPUTS (CABRAT03 SWITCHED ACCESS, CABRAT04 SPECIAL
* ACCESS, CABRAT05 UNE) BACK INTO ONE STREAM BY BAN AND SEQUENCE
* AHEAD OF CABRAT11.  ALL THREE INPUTS MUST ALREADY BE IN BAN
* AND SEQUENCE ORDER OR THE MERGE PRODUCES GARBAGE SILENTLY -
* SORT DOES NOT VALIDATE MERGE INPUT ORDER.
*
* THE CYCLE SELECTION HAS LEFT THIS CARD.  ONLY RECORDS WHOSE
* BILL PERIOD AT COLUMNS 180 THROUGH 185 MATCHES THE CURRENT
* CYCLE ARE KEPT, AND THAT LITERAL IS NOW HELD IN THE E35 EXIT
* CABSXCYC.  OPERATIONS TYPED IT ONTO THIS CARD ON THE FIRST
* WORKING DAY OF EACH BILL PERIOD; THE SAME MAINTENANCE IS NOW A
* RECOMPILE AND A RELINK OF THAT MODULE ON THE SAME DAY.
* CABSXCYC ALSO COMPARES EACH RECORD'S KEY WITH THE ONE BEFORE
* IT AND REPORTS A COUNT OF DESCENDING KEYS, WHICH IS THE ONLY
* CHECK THIS STEP HAS ON MERGE INPUT ORDER.
*
* EQUAL KEY HANDLING IS NOT CODED.  BAN AND SEQUENCE ARE UNIQUE
* ACROSS THE THREE STREAMS, SO THERE IS NO EQUAL KEY ORDER TO
* GUARANTEE.
*
* THE CYCLE LITERAL IS NO LONGER READABLE FROM THIS CARD.
 MERGE FIELDS=(9,13,CH,A,22,9,CH,A)
 RECORD TYPE=F,LENGTH=(200)
 MODS E35=(CABSXCYC,4096,SORTEXIT,N)
 END
